13-rails-intro/trainshop/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # this:
    resources :trains, only: [:index, :show]

  # is equivalent programmaticaly to this
    # get '/trains', to: 'trains#index', as: 'trains'
    # get '/trains/:id', to: 'trains#show', as: 'train'
end

13-rails-intro/trainshop/app/models/train.rb
class Train < ApplicationRecord
end

13-rails-intro/trainshop/app/controllers/trains_controller.rb
class TrainsController < ApplicationController

  def index
    @trains = Train.all
  end

  def show
    @train = Train.find(params[:id])
  end

end

13-rails-intro/trainshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

13-rails-intro/trainshop/app/views/trains/index.html.erb
<h1>trains</h1>

<% @trains.each do |train| %>
  <p>
    <%= link_to train.name, train %>
    costs
    <%= train.price %>
    and it is
    <% if train.cool %>
      cool
    <% else %>
      <span style="color: red;"> not cool </span>
    <% end %>
  </p>
<% end %>

13-rails-intro/trainshop/app/views/trains/show.html.erb
<h2> <%= @train.name  %> </h2>

<p> £<%= @train.price %> </p>

<%= link_to 'trains', trains_path %>