18-rails-auth-2/docoffice/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :doctors
  resources :chickens

  # user account management
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  # sessions management
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy', as: 'logout'
end

18-rails-auth-2/docoffice/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

18-rails-auth-2/docoffice/app/models/chicken.rb
class Chicken < ApplicationRecord
  belongs_to :doctor
end

18-rails-auth-2/docoffice/app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :speciality, presence: true

  has_many :chickens
  has_many :appointments
  has_many :patients, through: :appointments
end

18-rails-auth-2/docoffice/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

18-rails-auth-2/docoffice/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
end

18-rails-auth-2/docoffice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new
    end
  end

  def logged_in?
    !!current_user.id
  end

  def authorized?
    if !logged_in?
      flash[:authorized] = "you are not logged in"
      redirect_to login_path and return
    end
  end

  def authorized_for(target_user_id)
    if current_user.id != target_user_id.to_i && current_user.admin != true
      flash[:authorized] = "You cannot view a page that does not belong to you!"
      redirect_to doctors_path
    end
  end
end

18-rails-auth-2/docoffice/app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  before_action :find_chicken, only: [:show, :edit, :update, :destroy]

  def index
    @chickens = Chicken.all
  end

  def show
  end

  def new
    @chicken = Chicken.new
  end

  def create
    @chicken = Chicken.create(chicken_params)
    redirect_to chickens_path
  end

  def edit
  end

  def update
    @chicken.update(chicken_params)
    redirect_to chicken_path(@chicken)
  end

  def destroy
    @chicken.destroy
  end

  private

  def find_chicken
    @chicken = Chicken.find(params[:id])
  end

  def chicken_params
    params.require(:chicken).permit(:name, :age, :feathers_num, :doctor_id)
  end

end

18-rails-auth-2/docoffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
    @chickens = Chicken.all
  end

  def create
    @doctor = Doctor.create(doctor_params)
    if @doctor.valid?
      redirect_to doctors_path
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to new_doctor_path
    end
  end

  def edit
    @chickens = Chicken.all
  end

  def update
    @doctor.update(doctor_params)
    redirect_to doctor_path(@doctor)

  end

  def destroy
    @doctor.destroy
  end

  private

  def find_doc
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :speciality, chicken_ids: [], patient_ids: [])
  end

end

18-rails-auth-2/docoffice/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to doctors_path
    else
      flash[:errors] = ["invalid username or password"]
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

18-rails-auth-2/docoffice/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    authorized_for(params[:id])
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to doctors_path
    else
      redirect_to signup_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end

end

18-rails-auth-2/docoffice/app/helpers/application_helper.rb
module ApplicationHelper
end

18-rails-auth-2/docoffice/app/views/chickens/_form.html.erb
<%= link_to 'back', chickens_path %>

<%= form_for @chicken do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :feathers_num %>
  <%= f.number_field :feathers_num %>

  <%= f.collection_select(:doctor_id, Doctor.all, :id, :name) %>

  <%= f.submit %>
<% end %>

18-rails-auth-2/docoffice/app/views/chickens/edit.html.erb
<h2>Edit a chicken</h2>

<%= render 'form' %>

18-rails-auth-2/docoffice/app/views/chickens/index.html.erb
<h2>All chickens</h2>

<%= link_to 'create a chicken', new_chicken_path %>

<ul>
  <% @chickens.each do |chicken| %>
    <li>
      <%= link_to chicken.name, chicken %> | <%= link_to 'edit', edit_chicken_path(chicken) %>
    </li>
  <% end %>
</ul>

18-rails-auth-2/docoffice/app/views/chickens/new.html.erb
<h2>Create a new chicken</h2>

<%= render 'form' %>

18-rails-auth-2/docoffice/app/views/chickens/show.html.erb
<h2> <%= @chicken.name %> </h2>

<p> <%= @chicken.age %> </p>

<% if @chicken.doctor %>
  <p>This chicken belongs to <%= link_to @chicken.doctor.name, @chicken.doctor %> </p>
<% else %>
  <p>This chicken is free</p>
<% end %>

<%= link_to 'see all chickens', chickens_path  %>

18-rails-auth-2/docoffice/app/views/doctors/_form.html.erb
<%= link_to 'back', doctors_path %>

<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :speciality %>
  <%= f.text_field :speciality %>

  <hr>
  
  <h2>Chickens</h2>

  <%= f.collection_check_boxes(:chicken_ids, @chickens, :id, :name) %>

  <hr>

  <h2>Patients</h2>

  <%= f.collection_check_boxes(:patient_ids, Patient.all, :id, :name) %>

  <hr>

  <%= f.submit %>
<% end %>

18-rails-auth-2/docoffice/app/views/doctors/edit.html.erb
<h2>Edit a doctor</h2>

<%= render 'form' %>

18-rails-auth-2/docoffice/app/views/doctors/index.html.erb
<h2>All doctors</h2>

<%= link_to 'create a new doc', new_doctor_path %>

<ul>
  <% @doctors.each do |doc| %>
    <li>
      <%= link_to doc.name, doc %>
    </li>
  <% end %>
</ul>

18-rails-auth-2/docoffice/app/views/doctors/new.html.erb
<h2>Create a new doctor</h2>

<%= render 'form' %>

18-rails-auth-2/docoffice/app/views/doctors/show.html.erb
<h2> <%= @doctor.name %> </h2>

<p> <%= @doctor.speciality %> </p>

<p>Chickens:</p>

<% @doctor.chickens.each do |c| %>
  <p> --- <%= c.name %> </p>
<% end %>

<p>Patients:</p>

<% @doctor.patients.each do |p| %>
  <p> --- <%= p.name %> </p>
<% end %>

<%= link_to 'see all doctors', doctors_path  %>

18-rails-auth-2/docoffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docoffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'Doctor app', '/doctors'%></h1>

    <% if !logged_in? %>
      <%= link_to 'login', login_path %>
      <%= link_to 'signup', '/signup' %>
    <% else %>
      <h3> Hello, <%= current_user.name  %> </h3>
      <%=  link_to "log out", logout_path, method: "post" %>
      <%= link_to 'my patient record', user_path(current_user.id) %>
    <% end %>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |e| %>
          <li style="color: red;">
            <%= e %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if flash[:authorized] %>
      <p style="color: red;">
        <%= flash[:authorized] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

18-rails-auth-2/docoffice/app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user, :url => "/signup" do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit %>
<% end %>

18-rails-auth-2/docoffice/app/views/users/show.html.erb
<h2> <%= @user.name %> personal important information page </h2>

<%= link_to 'go back', '/doctors' %>